import './globals.css'
import type { Metadata } from 'next'
import { Inter, Forum } from 'next/font/google'

const inter = Inter({ weight:["400","700"], subsets: ['latin'], variable: '--font-inter', display: 'swap', });
const forum = Forum({ weight:"400", subsets: ['latin'], variable: '--font-forum', display: 'swap', });
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${inter.variable} ${forum.variable}`}>{children}</body>
    </html>
  )
}
